<?xml version="1.0"?>
<package format="3">
  <name>jetracer_driver</name>
  <version>0.0.1</version>
  <description>JetRacer ROS2 serial driver</description>
  <maintainer email="you@email.com">you</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
